import {
	Diamond,
	Home,
	HomeIcon,
	Info,
	Menu,
	User2,
	Library,
	Calculator,
	Globe,
	TextCursorInput,
	MessageCircle,
	Info as InfoIcon,
	BookOpen,
	Clock,
	Map,
	CircleArrowRight,
	TicketCheck,
	Ban,
	BookMarked,
	Waypoints,
	Equal,
	HeartHandshake,
	HandCoins,
	ServerCrash,
} from 'lucide-react'

export const icons = {
	home: <HomeIcon className="h-full" />,
	checklist: <Menu className="h-full" />,
	note: <Info className="h-full" />,
	tipify: <Diamond className="h-full" />,
	admin: <User2 className="h-full" />,
	library: <Library className="h-full" />,
	calc: <Calculator className="h-full" />,
	web: <Globe className="h-full" />,
	textSlash: <TextCursorInput className="h-full" />,
	comments: <MessageCircle className="h-full" />,
	info: <InfoIcon className="h-full" />,
	catalogue: <BookOpen className="h-full" />,
	timeLine: <Clock className="h-full" />,
	map: <Map className="h-full" />,
	circleArrowRight: <CircleArrowRight className="h-full" />,
	ticketCheck: <TicketCheck className="h-full" />,
	ban: <Ban className="h-full" />,
	bookOpen: <BookOpen className="h-full" />,
	bookMarket: <BookMarked className="h-full" />,
	waypoints: <Waypoints className="h-full" />,
	equal: <Equal className="h-full" />,
	heartHandshake: <HeartHandshake className="h-full" />,
	handCoins: <HandCoins className="h-full" />,
	serverCrash: <ServerCrash className="h-full" />,
}
